### ISSUE TITLE
Disable focus on click

### ISSUE THREAD

**Issue by balazsorban44** [dmtrKovalenko/material-ui-datetimepicker#4]
Hi, first it is an amazing expansion of Material UI!

But I have a question. When I am on a mobile device and want to select the date time picker, my keyboard jumps up, which is unnecessary, since you select the date by clicking on it. Is there a way to tell the component, not to focus on the input field on click, to prevent the keyboard jumping up?

Thanks, Balázs

**Comment by dmtrKovalenko** [comment]
Good day Balázs.
The bug was reproduced, so will fix that in the nearest release

**Comment by balazsorban44** [comment]
Thanks!

**Comment by dmtrKovalenko** [comment]
:raised_hands: Fixed in 0.1.9

**Comment by balazsorban44** [comment]
Could you tell me how to implement the solution? :) Cause it does not work for me, after updating to 0.1.9. I tried to figure it from your source code, but I did not manage.

**Comment by dmtrKovalenko** [comment]
https://github.com/dmtrKovalenko/material-ui-datetimepicker/pull/6
Review this pull request

**Comment by balazsorban44** [comment]
As I can see, you added a handleFocus() method to the TextField, which runs on focus. 
But as I said, it did not resolve my problem. In fact, I also checked your online demo page, and I get the jumping keyboard there as well!

**Comment by dmtrKovalenko** [comment]
I am sorry, seems I forgot to update demo :anguished:
I've tested it a bit for real devices - it works properly. I will update demo but take it from me, it works for 0.1.9

**Comment by balazsorban44** [comment]
Could you tell me how to apply to fix, please?

**Comment by dmtrKovalenko** [comment]
I`ve fixed that in 2.0

**Comment by balazsorban44** [comment]
I get his after updating to 2.0

![image](https://user-images.githubusercontent.com/18369201/31347041-5203f5a8-ad1b-11e7-86d0-8455a1efcab4.png)


And the problem still exists, even in your demo.
![image](https://user-images.githubusercontent.com/18369201/31347114-8cdf5c6c-ad1b-11e7-9198-413f9050d904.png)


Sorry for nagging you so much, I appreciate the effort you put into this module. I use it as a part of a school project, and we are getting near the deadline, would be awesome to have this small thing fixed until then. Keep up the good work!

**Comment by dmtrKovalenko** [comment]
@balazsorban44  🙌  At last, I`ve updated demo, you can check it now :)

**Comment by balazsorban44** [comment]
Yes, it works fine for me as well! Thanks :+1:
